
from tkinter import *
r=Tk()
r.geometry("500x500")

l0=Label(r,text="MARK SHEET")
l0.grid(row=0,column=6)
l1=Label(r,text="STUDENT NAME")
l1.grid(row=2,column=1)
l2=Label(r,text="CLASS")
l2.grid(row=3,column=1)
l3=Label(r,text="SECTION")
l3.grid(row=4,column=1)
l4=Label(r,text="SCHOOL NAME")
l4.grid(row=5,column=1)
l5=Label(r,text="TAMIL")
l5.grid(row=6,column=1)
l6=Label(r,text="ENGLISH")
l6.grid(row=7,column=1)
l7=Label(r,text="MATHS")
l7.grid(row=8,column=1)
l8=Label(r,text="PHYSICS")
l8.grid(row=9,column=1)
l9=Label(r,text="CHEMISTRY")
l9.grid(row=10,column=1)
l10=Label(r,text="BIOLOGY")
l10.grid(row=11,column=1)
l11=Label(r,text="TOTAL MARKS")
l11.grid(row=12,column=1)

e1=Entry(r)
e1.grid(row=2,column=2)
e2=Entry(r)
e2.grid(row=3,column=2)
e3=Entry(r)
e3.grid(row=4,column=2)
e4=Entry(r)
e4.grid(row=5,column=2)
e5=Entry(r)
e5.grid(row=6,column=2)
e6=Entry(r)
e6.grid(row=7,column=2)
e7=Entry(r)
e7.grid(row=8,column=2)
e8=Entry(r)
e8.grid(row=9,column=2)
e9=Entry(r)
e9.grid(row=10,column=2)
e10=Entry(r)
e10.grid(row=11,column=2)
e11=Entry(r)
e11.grid(row=12,column=2)

def add():
    a=int(e5.get())
    b=int(e6.get())
    c=int(e7.get())
    d=int(e8.get())
    e=int(e9.get())
    f=int(e10.get())
    g=a+b+c+d+e+f
    e11.insert(0,g)

b=Button(r,text="ENTER",command=lambda:add())
b.grid(row=12,column=3)


