
from tkinter import *
k=Tk()
k.geometry("500x500")

l1=Label(k,text="NAME:")
l1.grid(row=1,column=2)
l2=Label(k,text="AGE:")
l2.grid(row=2,column=2)
l3=Label(k,text="FATHER NAME:")
l3.grid(row=3,column=2)
l4=Label(k,text="MOTHER NAME:")
l4.grid(row=4,column=2)
l5=Label(k,text="SCHOOL:")
l5.grid(row=5,column=2)
l6=Label(k,text="PLACE:")
l6.grid(row=6,column=2)
l7=Label(k,text="TAMIL MARK:")
l7.grid(row=7,column=2)
l8=Label(k,text="ENGLISH MARK:")
l8.grid(row=8,column=2)
l9=Label(k,text="MATHS MARK:")
l9.grid(row=9,column=2)
l10=Label(k,text="PHYSICS MARK:")
l10.grid(row=10,column=2)
l11=Label(k,text="CHEMISTRY MARK:")
l11.grid(row=11,column=2)
l12=Label(k,text="BIOLOGY MARK:")
l12.grid(row=12,column=2)
l13=Label(k,text="TOTAL MARK:")
l13.grid(row=13,column=2)

e1=Entry(k)
e1.grid(row=1,column=3)
e2=Entry(k)
e2.grid(row=2,column=3)
e3=Entry(k)
e3.grid(row=3,column=3)
e4=Entry(k)
e4.grid(row=4,column=3)
e5=Entry(k)
e5.grid(row=5,column=3)
e6=Entry(k)
e6.grid(row=6,column=3)
e7=Entry(k)
e7.grid(row=7,column=3)
e8=Entry(k)
e8.grid(row=8,column=3)
e9=Entry(k)
e9.grid(row=9,column=3)
e10=Entry(k)
e10.grid(row=10,column=3)
e11=Entry(k)
e11.grid(row=11,column=3)
e12=Entry(k)
e12.grid(row=12,column=3)
e13=Entry(k)
e13.grid(row=13,column=3)

def studentform():
    f=open("studentform.text","a")
    f.write("\n"+e1.get()+"\n"+e2.get()+"\n"+e3.get()+"\n"+e4.get()+"\n"+e5.get()+"\n"+e6.get()+"\n"+e7.get()+"\n"+e8.get()+"\n"+e9.get()+"\n"+e10.get()+"\n"+e11.get()+"\n"+e2.get()+"\n"+e13.get())
    a=int(e7.get())
    b=int(e8.get())
    c=int(e9.get())
    d=int(e10.get())
    e=int(e11.get())
    f=int(e12.get())
    g=a+b+c+d+e+f
    e13.insert(0,g)

b=Button(k,text="SAVE",command=lambda:studentform())
b.grid(row=13,column=4)

k.mainloop
    
