
import tkinter
from tkinter import *
from tkinter import ttk,font
from PIL import ImageTk,Image

def customerlog(k):
    k.destroy()
    k=Tk()
    k.geometry("1000x700")
    k.title("SPORTS")
    frame=Frame(k,width=1500,height=50,bg="blue")
    frame.pack()
    f=font.Font(weight="bold",family="Jazz LET",size=25)
    x=Label(frame,text="Sports Items",font=f)
    x.configure(bg="red",fg="yellow")
    x.place(relx=0.44,rely=0.1)

    frame=Frame(k,width=1500,height=800)
    frame.place(anchor="s",relx=0.50,rely=0.94)
    img=ImageTk.PhotoImage(Image.open("picture.jpg"))
    label=Label(frame,image=img)
    label.pack()

    
    f=font.Font(weight="bold",family="Jazz LET",size=20)
    l=Label(frame,text="GAMES AND INFORMATION",font=f,bg="white").place(relx=0.36,rely=0.17)

    d=font.Font(k,weight="bold",family="TIMES NEW ROMAN",size=15)
    l=Label(frame,text="CRICKET",font=d,bg="green").place(relx=0.10,rely=0.23)
    l=Label(frame,text="FOOTBALL",font=d,bg="orange").place(relx=0.45,rely=0.23)
    l=Label(frame,text="HOCKEY",font=d,bg="blue").place(relx=0.82,rely=0.23)

    l1=Entry(frame,background="pink")
    l1.place(relx=0.09,rely=0.31)
    l2=Entry(frame,background="lightgreen")
    l2.place(relx=0.45,rely=0.31)
    l3=Entry(frame,background="skyblue")
    l3.place(relx=0.81,rely=0.31)
    b=Button(frame,text="SAVE",font=d,bg="skyblue")
    b.place(relx=0.47,rely=0.94)
    b=Button(k,text="TOTAL",font=f,bg="red",command=lambda:customerlog())
    b.place(relx=0.55,rely=0.85)
    
    frame=Frame(k,width=1500,height=50,bg="yellow")
    frame.pack()
    frame.place(relx=0.0,rely=0.94)
    f=font.Font(weight="bold",family="Jazz LET",size=20)
    x=Label(frame,text="Sandy Sports Materials",font=f)
    x.configure(bg="yellow",fg="black")
    x.place(relx=0.36,rely=0.1)
    
    k.mainloop()
    

def file (a,b,c,d,k):
    r=a+" "+b+" "+c+" "+d+"\n"
    f=open("sports.txt","a")
    f.write(r) 

def customer_reg(k):
    k.destroy()
    k=Tk()
    k.geometry("1000x700")
    k.title("SPORTS")
    frame=Frame(k,width=1500,height=50,bg="blue")
    frame.pack()
    f=font.Font(weight="bold",family="Jazz LET",size=25)
    x=Label(frame,text="Sports Details",font=f)
    x.configure(bg="red",fg="yellow")
    x.place(relx=0.42,rely=0.1)

    frame=Frame(k,width=1500,height=800)
    frame.place(anchor="s",relx=0.50,rely=0.95)
    img=ImageTk.PhotoImage(Image.open("images.jpg"))
    label=Label(frame,image=img)
    label.pack()

    
    f=font.Font(weight="bold",family="Jazz LET",size=20)
    l=Label(frame,text="BALLS ITEMS",font=f,bg="green",fg="orange").place(relx=0.43,rely=0.0)

    t=font.Font(k,weight="bold",family="TIMES NEW ROMAN",size=15)
    
    l1=Entry(frame,background="yellow")
    l1.place(relx=0.02,rely=0.21)
    l2=Entry(frame,background="orange")
    l2.place(relx=0.19,rely=0.22)
    l3=Entry(frame,background="lightgreen")
    l3.place(relx=0.36,rely=0.21)
    l4=Entry(frame,background="lightblue")
    l4.place(relx=0.54,rely=0.22)
    l5=Entry(frame,background="skyblue")
    l5.place(relx=0.71,rely=0.22)
    l6=Entry(frame,background="pink")
    l6.place(relx=0.87,rely=0.21)
    l7=Entry(frame,background="yellow")
    l7.place(relx=0.02,rely=0.54)
    l8=Entry(frame,background="orange")
    l8.place(relx=0.18,rely=0.54)
    l9=Entry(frame,background="lightgreen")
    l9.place(relx=0.36,rely=0.55)
    l10=Entry(frame,background="lightblue")
    l10.place(relx=0.55,rely=0.55)
    l11=Entry(frame,background="skyblue")
    l11.place(relx=0.71,rely=0.53)
    l12=Entry(frame,background="pink")
    l12.place(relx=0.87,rely=0.55)
    l13=Entry(frame,background="yellow")
    l13.place(relx=0.02,rely=0.90)
    l14=Entry(frame,background="orange")
    l14.place(relx=0.18,rely=0.90)
    l15=Entry(frame,background="lightgreen")
    l15.place(relx=0.36,rely=0.89)
    l16=Entry(frame,background="lightblue")
    l16.place(relx=0.55,rely=0.89)
    l17=Entry(frame,background="skyblue")
    l17.place(relx=0.71,rely=0.85)
    l18=Entry(frame,background="pink")
    l18.place(relx=0.87,rely=0.89)
    b=Button(frame,text="LOGIN",font=t,bg="orange")
    b.place(relx=0.47,rely=0.84)

    frame=Frame(k,width=1500,height=50,bg="yellow")
    frame.pack()
    frame.place(relx=0.0,rely=0.94)
    f=font.Font(weight="bold",family="Jazz LET",size=20)
    x=Label(frame,text="Sandy Sports Materials",font=f)
    x.configure(bg="yellow",fg="black")
    x.place(relx=0.36,rely=0.1)
    k.mainloop()

def adminpage(k):
    k.destroy()
    k=Tk()
    k.geometry("1000x700")
    k.title("SPORTS")
    frame=Frame(k,width=1500,height=50,bg="yellow")
    frame.pack()
    f=font.Font(weight="bold",family="Jazz LET",size=25)
    x=Label(frame,text="GAMES",font=f)
    x.configure(bg="yellow",fg="black")
    x.place(relx=0.45,rely=0.1)

    frame=Frame(k,width=500,height=400,bg="light blue").place(relx=0.35,rely=0.2)
    f=font.Font(weight="bold",family="Jazz LET",size=20)
    l=Label(frame,text="SPORTS FORM",font=f,bg="orange").place(relx=0.47,rely=0.2)

    y=font.Font(k,weight="bold",family="times new roman",size=15)
    l=Label(frame,text="USERNAME",font=y,bg="pink").place(relx=0.12,rely=0.2)
    l=Label(frame,text="PASSWORD",font=y,bg="yellow").place(relx=0.12,rely=0.3)
    l=Label(frame,text="EMAIL ID",font=y,bg="purple").place(relx=0.12,rely=0.4)
    l=Label(frame,text="PHONE NUMBER",font=y,bg="red").place(relx=0.12,rely=0.5)
    l=Label(frame,text="STORE NAME",font=y,bg="light green").place(relx=0.12,rely=0.6)
    l=Label(frame,text="WHATSAPP",font=y,bg="light blue").place(relx=0.12,rely=0.7)
    l=Label(frame,text="ADDRESS",font=y,bg="light blue").place(relx=0.12,rely=0.8)
    l=Label(frame,text="CITY",font=y,bg="red").place(relx=0.60,rely=0.2)
    l=Label(frame,text="STATE",font=y,bg="orange").place(relx=0.60,rely=0.3)
    l=Label(frame,text="COUNTRY",font=y,bg="skyblue").place(relx=0.60,rely=0.4)

    l1=Entry(frame)
    l1.place(relx=0.30,rely=0.20)
    l2=Entry(frame)
    l2.place(relx=0.30,rely=0.30)
    l3=Entry(frame)
    l3.place(relx=0.30,rely=0.40)
    l4=Entry(frame)
    l4.place(relx=0.30,rely=0.50)
    l5=Entry(frame)
    l5.place(relx=0.30,rely=0.60)
    l6=Entry(frame)
    l6.place(relx=0.30,rely=0.70)
    l7=Entry(frame)
    l7.place(relx=0.30,rely=0.80)
    l8=Entry(frame)
    l8.place(relx=0.80,rely=0.20)
    l9=Entry(frame)
    l9.place(relx=0.80,rely=0.30)
    l10=Entry(frame)
    l10.place(relx=0.80,rely=0.40)
    b=Button(frame,text="LOGIN",font=y,bg="pink")
    b.place(relx=0.48,rely=0.88)

    frame=Frame(k,width=1500,height=50,bg="yellow")
    frame.pack()
    frame.place(relx=0.0,rely=0.94)
    f=font.Font(weight="bold",family="Jazz LET",size=20)
    x=Label(frame,text="sandy sports materials",font=y)
    x.configure(bg="yellow",fg="black")
    x.place(relx=0.45,rely=0.1)
    k.mainloop()

def admin(a,b,k):
    if(a=="admin" and b=="admin"):
        adminpage(k)
    else:
        adminlog(k)

def adminlog(k):
    k.destroy()
    k=Tk()
    k.geometry("1000x700")
    k.title("SPORTS")
    frame=Frame(k,width=1500,height=50,bg="yellow")
    frame.pack()
    f=font.Font(weight="bold",family="Jazz LET",size=25)
    x=Label(frame,text="SPORTS REGISTER FORM",font=f)
    x.configure(bg="yellow",fg="black")
    x.place(relx=0.38,rely=0.0)

    frame=Frame(k,width=1000,height=700)
    frame.place(anchor="s",relx=0.50,rely=0.96)
    img=ImageTk.PhotoImage(Image.open("logo.jpg"))
    label=Label(frame,image=img)
    label.pack()

    f=font.Font(k,weight="bold",family="times new roman",size=20)
    l=Label(frame,text="SPORTS INFORMATION",font=f,bg="white").place(relx=0.41,rely=0.07)
        
    s=font.Font(k,weight="bold",family="times new roman",size=15)
    l=Label(frame,text="USERNAME",font=s,bg="pink").place(relx=0.12,rely=0.2)
    l=Label(frame,text="PASSWORD",font=s,bg="yellow").place(relx=0.12,rely=0.3)
    l=Label(frame,text="EMAIL ID",font=s,bg="purple").place(relx=0.12,rely=0.4)
    l=Label(frame,text="PHONE NUMBER",font=s,bg="red").place(relx=0.12,rely=0.5)
    l=Label(frame,text="STORE NAME",font=s,bg="light green").place(relx=0.12,rely=0.6)
    l=Label(frame,text="WHATSAPP",font=s,bg="light blue").place(relx=0.12,rely=0.7)
    l=Label(frame,text="ADDRESS",font=s,bg="light blue").place(relx=0.12,rely=0.8)
    l=Label(frame,text="CITY",font=s,bg="red").place(relx=0.60,rely=0.2)
    l=Label(frame,text="STATE",font=s,bg="orange").place(relx=0.60,rely=0.3)
    l=Label(frame,text="COUNTRY",font=s,bg="skyblue").place(relx=0.60,rely=0.4)

    l1=Entry(frame)
    l1.place(relx=0.30,rely=0.20)
    l2=Entry(frame)
    l2.place(relx=0.30,rely=0.30)
    l3=Entry(frame)
    l3.place(relx=0.30,rely=0.40)
    l4=Entry(frame)
    l4.place(relx=0.30,rely=0.50)
    l5=Entry(frame)
    l5.place(relx=0.30,rely=0.60)
    l6=Entry(frame)
    l6.place(relx=0.30,rely=0.70)
    l7=Entry(frame)
    l7.place(relx=0.30,rely=0.80)
    l8=Entry(frame)
    l8.place(relx=0.80,rely=0.20)
    l9=Entry(frame)
    l9.place(relx=0.80,rely=0.30)
    l10=Entry(frame)
    l10.place(relx=0.80,rely=0.40)
    b=Button(frame,text="LOGIN",font=s,bg="pink")
    b.place(relx=0.48,rely=0.88)

    frame=Frame(k,width=1500,height=50,bg="yellow")
    frame.pack()
    frame.place(relx=0.0,rely=0.94)
    f=font.Font(weight="bold",family="Jazz LET",size=20)
    x=Label(frame,text="Sandy Sports Materials",font=f)
    x.configure(bg="yellow",fg="black")
    x.place(relx=0.36,rely=0.1)
    k.mainloop()

    f=open("sports.text","a")
    f.write(k)

    b1=Button(k,text="SAVE",command=lambda:())
    b1.place(relx=0.50,rely=0.9)
    

def Home():
    #Home page
    k=Tk() 
    k.geometry("1000x700")
    k.title("SPORTS")
    frame=Frame(k,width=1500,height=50,bg="yellow")
    frame.pack()
    f=font.Font(weight="bold",family="Times New Roman",size=25)
    x=Label(frame,text="SPORTS",font=f)
    x.configure(bg="yellow",fg="black")
    x.place(relx=0.45,rely=0.1)

    frame=Frame(k,width=1000,height=700)
    frame.place(anchor="s",relx=0.50,rely=0.98)
    img=ImageTk.PhotoImage(Image.open("sports.jpg"))
    label=Label(frame,image=img)
    label.pack()

    f=font.Font(k,weight="bold",family="Jazz LET",size=20)
    b=Button(k,text="Sports Items",font=f,bg="orange",activebackground="#FC92C4",command=lambda:customerlog(k)).place(relx=0.10,rely=0.5)
    c=Button(k,text="Sports Details",font=f,bg="white",activebackground="#FC92C4",command=lambda:customer_reg(k)).place(relx=0.40,rely=0.5)
    d=Button(k,text="Games Login",font=f,bg="lightgreen",activebackground="#FC92C4",command=lambda:adminlog(k)).place(relx=0.71,rely=0.5)
    
    frame=Frame(k,width=1500,height=50,bg="yellow")
    frame.pack()
    frame.place(relx=0.0,rely=0.94)
    f=font.Font(k,weight="bold",family="Times New Roman",size=20)
    x=Label(frame,text="Sandy Sports Materials",font=f)
    x.configure(bg="yellow",fg="black")
    x.place(relx=0.38,rely=0.1)

    k.mainloop()


Home()
                                                             