
from tkinter import *
from tkinter import ttk,font
from PIL import ImageTk,Image

bill=Tk()
bill.geometry("700x700")
frame=Frame(bill,width=670,height=700,bg="BLACK")
frame.place(relx=0.3,rely=0.01)
frame1=Frame(bill,width=500,height=700)
frame.pack()
frame1.place(anchor="n",relx=0.6,rely=0.95)
img=ImageTk.PhotoImage(Image.open("photo.jpg"))
label=Label(frame,image=img)
label.pack()
f=font.Font(weight="bold",family="helvetica",size=30)
l0=Label(bill,text="SPORTS MATERIAL",font=f,bg="burlywood1")
l0.place(relx=0.35,rely=0.0)
f1=font.Font(weight="bold",family="CALIBRI",size=15)
l1=Label(bill,text="BASKET BALL:",font=f1,bg="bisque1")
l1.place(relx=0.3,rely=0.1)
l2=Label(bill,text="VOLLEY BALL:",font=f1,bg="bisque1")
l2.place(relx=0.3,rely=0.2)
l3=Label(bill,text="TENNIS BALL:",font=f1,bg="bisque1")
l3.place(relx=0.3,rely=0.3)
l4=Label(bill,text="CRICKET BALL:",font=f1,bg="bisque1")
l4.place(relx=0.3,rely=0.4)
l5=Label(bill,text="FOOT BALL:",font=f1,bg="bisque1")
l5.place(relx=0.3,rely=0.5)
l6=Label(bill,text="CRICKET BAT:",font=f1,bg="bisque1")
l6.place(relx=0.3,rely=0.6)
l7=Label(bill,text="HOCKEY STICK:",font=f1,bg="bisque1")
l7.place(relx=0.3,rely=0.7)
l8=Label(bill,text="BOXING GLOVES:",font=f1,bg="bisque1")
l8.place(relx=0.3,rely=0.8)
l9=Label(bill,text="BATMINTON RACQUET:",font=f1,bg="bisque1")
l9.place(relx=0.3,rely=0.9)

mystr=StringVar()
mystr.set('0')
mystr1=StringVar()
mystr1.set('0')
k=font.Font(weight="bold",family="times new roman",size=15)
a1=Entry(bill,font=k,bg="#7FFFD4")
a1.place(relx=0.5,rely=0.1)
a2=Entry(bill,font=k,bg="#7FFFD4")
a2.place(relx=0.5,rely=0.2)
a3=Entry(bill,font=k,bg="#7FFFD4")
a3.place(relx=0.5,rely=0.3)
a4=Entry(bill,font=k,bg="#7FFFD4")
a4.place(relx=0.5,rely=0.4)
a5=Entry(bill,font=k,bg="#7FFFD4")
a5.place(relx=0.5,rely=0.5)
a6=Entry(bill,font=k,bg="#7FFFD4")
a6.place(relx=0.5,rely=0.6)
a7=Entry(bill,font=k,bg="#7FFFD4")
a7.place(relx=0.5,rely=0.7)
a8=Entry(bill,font=k,bg="#7FFFD4")
a8.place(relx=0.5,rely=0.8)
a9=Entry(bill,font=k,bg="#7FFFD4")
a9.place(relx=0.5,rely=0.9)


def sportsmaterial():
    f=open("sportsmaterial.text","a")
    f.write("\n"+a1.get()+"\n"+a2.get()+"\n"+a3.get()+"\n"+a4.get()+"\n"+a5.get()+"\n"+a6.get()+"\n"+a7.get()+"\n"+a8.get()+"\n"+a9.get())
    a=int(a1.get())
    b=int(a2.get())
    c=int(a3.get())
    d=int(a4.get())
    e=int(a5.get())
    f=int(a6.get())
    g=int(a7.get())
    h=int(a8.get())
    i=int(a9.get())
    j=a+b+c+d+e+f+g+h+i
    print(j)
    mystr.set(str(j))
b=Button(bill,text="TOTAL",bg="#20B2AA",font=k,command=lambda:sportsmaterial())
b.place(relx=0.45,rely=0.95)

def materials():
    a=int(a1.get())
    b=int(a2.get())
    c=int(a3.get())
    d=int(a4.get())
    e=int(a5.get())
    f=int(a6.get())
    g=int(a7.get())
    h=int(a8.get())
    i=int(a9.get())
    j=a+b+c+d+e+f+g+h+i
    print(j)
    mystr1.set(str(j))
b1=Button(bill,text="SAVE",bg="#20B2AA",font=k,command=lambda:materials())
b1.place(relx=0.56,rely=0.95)

bill.mainloop()
